### ISSUE TITLE
Tracking issue to improve the bendsql

### ISSUE THREAD

**Issue by sundy-li** [databendlabs/bendsql#21]
To make the `databend-cli` works better, there are some tasks to do:

- [x] Better error message #22 
- [x] Support loading file as cli side settings #31 
- [x] Support display server progress (use indicatif crate) #26 
- [x]  Support control command #95 95
- [ ] Support display server logs
- [x] #182

**Comment by flaneur2020** [comment]
I guess this issue can be closed? there've made lots of progress since this issue created
